### ISSUE TITLE
[openy_map_lb] Amenities filters fail with content types that don't have amenities field

### ISSUE THREAD

**Issue by froboy** [open-y-subprojects/openy_map#75]
To test:
- create a Location Finder LB page
- add some Camp content (which doesn't have field_amenities on the content type)
- use the location filters
- observe console error
    > Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    > at map.js:1149:29

![SCR-20240409-jjhy](https://github.com/open-y-subprojects/openy_map/assets/238201/f563ca3d-62ba-431a-976c-cefff8e844b7)

**Comment by andrebonon** [comment]
This bug happens when a Camp is unpublish in English but published in other languages (FR for example).
I captured the same bug but I proposed a fix in a different way here: https://github.com/open-y-subprojects/openy_custom/issues/68

After the issue above gets merged, we'd need to edit the OpenyMapDataWrapper class that extends from DataWrapper, and replicate the solution with Language manager and a new condition for the query.
https://github.com/open-y-subprojects/openy_map/blob/main/src/OpenyMapDataWrapper.php#L23
